spring:
  jackson:
    default-property-inclusion: non_null
    property-naming-strategy: SNAKE_CASE
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
  jpa:
    generate-ddl: true

logging:
  level:
    com.example.myshop: DEBUG

api:
  url: https://ws.pagseguro.uol.com.br/v2/checkout?email=${PAGSEGURO_ACCOUNT_EMAIL}&token=${PAGSEGURO_ACCOUNT_TOKEN}
